In [48]:
import numpy as np
from numpy import linalg
import matplotlib.pyplot as plt
import copy

In [49]:
n = np.array([[1, 2, 3], [4, 5, 6]])

In [50]:
np.matmul(n,n.T)

array([[14, 32],
       [32, 77]])

In [188]:
def sgd(A, x, b, lr = 1e-3, tol = 1e-5, nmax = 1e3):
    rold = b-A.dot(x)
    iter_num = 0
    res = [linalg.norm(rold)/linalg.norm(b)]
    while iter_num < nmax:
        if res[iter_num] < tol:
            break
        iter_num += 1
        x = x + 2*lr*np.dot(np.transpose(A),rold)
        rnew = b-A.dot(x)
        res.append(linalg.norm(rnew)-linalg.norm(rold))
        rold = rnew
    return res, n, x

In [189]:
# def run_experiment(A, b, algo):
#     A = np.array([[1,1],[2,2],[3,3],[4,4]])
#     b = np.array([[1],[5],[5],[9]])
#     x = np.array([[0],[0]])
#     res, n, x1 = algo(A, x, b)
    
A = np.array([[1,1],[2,2],[3,3],[4,4]])
b = np.array([[1],[5],[5],[9]])
x = np.array([[0],[0]])
res, n, x1 = sgd(A, x, b)

In [190]:
x1

array([[0.124],
       [0.124]])

In [109]:
a

array([[3, 4]])

In [110]:
linalg.norm(a)

5.0

In [111]:
a1 = np.array([[3],[4]])
a2 = np.array([[3],[5]])

In [112]:
a2-a1

array([[0],
       [1]])

In [71]:
a2

array([[3, 4]])